name: CI workflow
on: [push, pull_request]
jobs:
  test:
    name: test (node ${{ matrix.node-version }}, ${{ matrix.os }}, graphql ${{ matrix.graphql-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24, 26]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        graphql-version: [16, 17]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install --ignore-scripts
      - name: Install graphql@${{ matrix.graphql-version }}
        run: npm install graphql@${{ matrix.graphql-version }} --ignore-scripts --no-save
      - name: Test
        run: npm run test
  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}